language: ruby
sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 1.9.3
      env: RUN=default
    - rvm: 2.0.0
      env: RUN=default
    - rvm: 2.1.0
      env: RUN=default
    - rvm: 2.2
      env: RUN=default
    - rvm: 2.2
      env: RUN=verify_rspec_specs
    - rvm: 2.2
      env: RUN=default RUNNER=node
    - rvm: 2.2
      env: RUN=verify_rspec_specs RUNNER=node

  allow_failures:
    - rvm: 2.2
      env: RUN=verify_rspec_specs
    - rvm: 2.2
      env: RUN=verify_rspec_specs RUNNER=node

before_install:
  - git submodule update --init

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc: "irc.freenode.org#opal"

script:
  - "bundle exec rake $RUN"
