language: ruby
sudo: false

cache:
  bundler: true
  directories:
  - phantom211
  - phantom20

matrix:
  fast_finish: true

  include:
    - rvm: 2.0.0
      env: RUN=mri_sanity_check
    - rvm: 2.1.8
      env: RUN=mri_sanity_check
    - rvm: 2.2.4
      env: RUN=mri_sanity_check
    - rvm: 2.3.0
      env: RUN=default
    - rvm: 2.3.0
      # PHANTOMJS env variable is not used but it makes it easier to differentiate this build in Travis
      # https://github.com/travis-ci/travis-ci/issues/3225 - Easiest way to use 2.0 on Travis
      env: PHANTOMJS=2.1 RUN=rake_only
      before_install:
        - git submodule update --init
        - "mkdir -p phantom211"
        - "export PATH=`pwd`/phantom211/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
        - "echo $PATH"
        - "pushd ."
        - "cd phantom211"
        - "ls phantom211/phantomjs-2.1.1-linux-x86_64/bin/phantomjs || curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
        - "ls phantom211/phantomjs-2.1.1-linux-x86_64/bin/phantomjs || tar xjvf phantomjs-2.1.1-linux-x86_64.tar.bz2"
        - "rm -rf phantomjs-2.1.1-linux-x86_64.tar.bz2"
        - "popd"
    - rvm: 2.2.4
      env: RUNNER=node RUN=rake_only

before_install:
  - git submodule update --init
  - "mkdir -p phantom20"
  - "export PATH=`pwd`/phantom20:$PATH"
  - "echo $PATH"
  - "pushd ."
  - "cd phantom20"
  - "ls phantom20/phantomjs || curl -L -O https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "ls phantom20/phantomjs || tar xjvf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "rm -rf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "popd"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc: "irc.freenode.org#opal"

script:
  - "bundle exec rake $RUN"
