language: ruby
sudo: false

cache:
  bundler: true
  directories:
  - node_modules
  - phantom20

matrix:
  fast_finish: true

  include:
    - rvm: 2.2.4
      env: RUN=mri_sanity_check
    - rvm: 2.3.0
      env: RUN=mri_sanity_check
    - rvm: 2.3.0
      env: RUN=rake_only
    - rvm: 2.3.0
      # PHANTOMJS env variable is not used but it makes it easier to differentiate this build in Travis
      env: PHANTOMJS=2.1 RUN=rake_only
      before_install:
        - gem update --system
        - git submodule update --init
        - npm install phantomjs-prebuilt # get rate limits from bitbucket download source
        - "export PATH=`pwd`/node_modules/phantomjs-prebuilt/bin:$PATH"
        - "echo $PATH"
    - rvm: 2.3.0
      env: RUNNER=node RUN=rake_only
    - rvm: 2.3.0
      env: RUN=rake_only
      gemfile: gemfiles/opal_master.gemfile
    - rvm: 2.3.0
      env: RUN=rake_only
      gemfile: gemfiles/opal_0.10_stable.gemfile

before_install:
  # Attempt to work around Travis issues - https://github.com/vcr/vcr/issues/582
  - gem update --system
  - git submodule update --init
  - "mkdir -p phantom20"
  - "export PATH=`pwd`/phantom20:$PATH"
  - "echo $PATH"
  - "pushd ."
  - "cd phantom20"
  - "ls phantom20/phantomjs || curl -L -O https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "ls phantom20/phantomjs || tar xjvf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "rm -rf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "popd"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc: "irc.freenode.org#opal"

script:
  - "bundle exec rake $RUN"
