language: ruby
sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 1.9.3
      # mime-types GEM >= 3 does not work with Ruby 1.9.3
      env: MT_GEM_OVERRIDE="true"
    - rvm: 2.0.0
    - rvm: 2.1.0
    - rvm: 2.2.3
    - rvm: 2.2.4
    - rvm: 2.3.0
    - rvm: 2.2.4
      # PHANTOMJS env variable is not used but it makes it easier to differentiate this build in Travis
      # https://github.com/travis-ci/travis-ci/issues/3225 - Easiest way to use 2.0 on Travis
      env: PHANTOMJS=2.0
      before_script:
        - "mkdir phantom20"
        - "export PATH=`pwd`/phantom20:$PATH"
        - "echo $PATH"
        - "pushd ."
        - "cd phantom20"
        - "curl -L -O https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
        - "tar xjvf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
        - "popd"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
    - rvm: 2.2.4
      env: RUNNER=node
    - rvm: 2.2.4
      gemfile: gemfiles/opal_master.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/opal_0.8.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/opal_0.9.stable.gemfile

  allow_failures:
    - gemfile: gemfiles/opal_master.gemfile

before_install:
  - git submodule update --init

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc: "irc.freenode.org#opal"

script:
  - "bundle exec rake"
