language: ruby
sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_install:
  - git submodule update --init

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc: "irc.freenode.org#opal"
