language: ruby
sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 2.0.0
    - rvm: 2.1.8
    - rvm: 2.2.4
    - rvm: 2.3.0
    - rvm: 2.2.4
      # PHANTOMJS env variable is not used but it makes it easier to differentiate this build in Travis
      # https://github.com/travis-ci/travis-ci/issues/3225 - Easiest way to use 2.0 on Travis
      env: PHANTOMJS=2.0
      before_install:
        - git submodule update --init
        - "mkdir phantom20"
        - "export PATH=`pwd`/phantom20:$PATH"
        - "echo $PATH"
        - "pushd ."
        - "cd phantom20"
        - "curl -L -O https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
        - "tar xjvf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
        - "popd"
    - rvm: 2.2.4
      env: RUNNER=node

before_install:
  - git submodule update --init
  - "mkdir phantom211"
  - "export PATH=`pwd`/phantom211/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "echo $PATH"
  - "pushd ."
  - "cd phantom211"
  - "curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
  - "tar xjvf phantomjs-2.1.1-linux-x86_64.tar.bz2"
  - "popd"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc: "irc.freenode.org#opal"

script:
  - "bundle exec rake"
